{% set name = "xpystac" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xpystac-{{ version }}.tar.gz
  sha256: 4e2bfcb351b3dab756b5016463f0c036f712844a18df2537289d91dc43f16221

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - xarray
    - pystac >=1.0.1

test:
  imports:
    - xpystac
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stac-utils/xpystac
  summary: Extend xarray.open_dataset to accept pystac objects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jsignell
